#pragma once

#include "CListCtrl_Sortable.h"

typedef enum euCallListColumnType_t
{
	EU_CALLS_LIST_COLUMN_NUMBER,
	EU_CALLS_LIST_COLUMN_NAME,
	EU_CALLS_LIST_COLUMN_PASSWD,
	EU_CALLS_LIST_COLUMN_DOMAIN,
	EU_CALLS_LIST_COLUMN_PORT,
	EU_CALLS_LIST_COLUMN_CALLED,
	EU_CALLS_LIST_COLUMN_DTMF,
	EU_CALLS_LIST_COLUMN_DTMF_DURATION,
	EU_CALLS_LIST_COLUMN_DURATION,
	EU_CALLS_LIST_COLUMN_REGTIMEOUT,
	EU_CALLS_LIST_COLUMN_STATUS,
	EU_CALLS_LIST_COLUMN_RTCP,
}EU_CALL_LIST_COLUMN;


class CListCtrl_SortItemsEx : public CListCtrl_Sortable
{
	DECLARE_MESSAGE_MAP();

public:
	virtual bool SortColumn(int columnIndex, bool ascending);
};